# Generated by Django 4.0 on 2022-02-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=100)),
                ('ultimo_nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['primeiro_nome', 'ultimo_nome'],
                'permissions': (('pode_manipular_proprietario', 'Manipula o cadastro de proprietários.'),),
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Entre com o tipo do veículo. Ex: Automóvel.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('cor', models.CharField(help_text='Entre com a cor predominante do veículo. Ex: Prata', max_length=20)),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garagem.proprietario')),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garagem.tipo')),
            ],
            options={
                'ordering': ['modelo'],
                'permissions': (('pode_manipular_veiculo', 'Manipula o cadastro de veículos.'),),
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('o', 'Ocupada'), ('m', 'Manutenção')], default='o', help_text='Situação da vaga', max_length=1)),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='garagem.veiculo')),
            ],
            options={
                'ordering': ['data_retirada'],
                'permissions': (('pode_manipular_vaga', 'Manipula o cadastro de vagas.'),),
            },
        ),
    ]
