# Generated by Django 4.0 on 2022-01-18 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'permissions': (('pode_manipular_veiculo', 'Manipula o cadastro de veículos.'),)},
        ),
    ]
